name       : dotnet
version    : 8.0.5
release    : 6
source     :
    - https://github.com/dotnet/dotnet/archive/refs/tags/v8.0.5.tar.gz : 1eede6abe709a5b4ba433beddcf9917b88916d6243b8c51a3664654bab6ea61c
homepage   : https://dot.net
license    : MIT
component  : programming.dotnet
summary    :
    - .NET runtime
    - sdk : .NET Development Kit
    - source-built-artifacts : Internal package for building .NET
description: .NET is a free, cross-platform, open-source developer platform for building many kinds of applications. It can run programs written in multiple languages, with C# being the most popular.
replaces   :
    - fsharp
networking : no
libsplit   : no
clang      : yes
strip      : no
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(krb5)
    - pkgconfig(libcurl)
    - pkgconfig(libssl)
    - pkgconfig(libunwind)
    - pkgconfig(lttng-ust)
    - pkgconfig(zlib)
    - dotnet-sdk
    - dotnet-source-built-artifacts
    - git
    - lldb-devel
rundeps    :
    - libicu
    - sdk :
        - dotnet
setup      : |
    %patch -p1 -i $pkgfiles/1005-default-opt-out-of-telemetry.patch
build      : |
    # disable stack protector
    CFLAGS="${CFLAGS//-fstack-protector-strong/-fno-stack-protector}"
    CXXFLAGS="${CXXFLAGS//-fstack-protector-strong/-fno-stack-protector}"
    # EXTRA_* flags are passed to the build system
    export EXTRA_CFLAGS="$CFLAGS"
    export EXTRA_CXXFLAGS="$CXXFLAGS"
    export EXTRA_LDFLAGS="$LDFLAGS"
    cp -r /usr/lib/dotnet .dotnet
    ln -sf /usr/share/dotnet/source-built-artifacts/Private.SourceBuilt.*.tar.gz prereqs/packages/archive/

    # setting `version` (any case) clobbers the msbuild version target
    unset CFLAGS CXXFLAGS LDFLAGS version
    ./prep.sh
    ./build.sh --clean-while-building --release-manifest $pkgfiles/release.json --with-sdk $PWD/.dotnet
install    : |
    # required bootstrap artifacts
    install -Dm00644 artifacts/x64/Release/Private.SourceBuilt.Artifacts.*.tar.gz -t $installdir/usr/share/dotnet/source-built-artifacts/
    install -Dm00644 artifacts/x64/Release/Private.SourceBuilt.Prebuilts.*.tar.gz -t $installdir/usr/share/dotnet/source-built-artifacts/

    # sdk
    install -dm00755 $installdir/usr/{bin,lib/dotnet,share/licenses/dotnet}
    tar -xf artifacts/x64/Release/dotnet-sdk-*.tar.gz -C $installdir/usr/lib/dotnet
    mv $installdir/usr/lib/dotnet/{LICENSE.txt,ThirdPartyNotices.txt} $installdir/usr/share/licenses/dotnet/
    ln -s /usr/lib/dotnet/dotnet $installdir/usr/bin/dotnet
    ln -s /usr/lib/dotnet/host/fxr/$version/libhostfxr.so $installdir/usr/lib/libhostfxr.so

    # prevents dotnet from having to search for the install location
    install -Dm00644 /dev/null $installdir/etc/dotnet/install_location
    echo "/usr/lib/dotnet/" > $installdir/etc/dotnet/install_location

    # completions
    install -Dm00644 src/sdk/scripts/register-completions.bash $installdir/usr/share/bash-completion/completions/dotnet
    install -Dm00644 src/sdk/scripts/register-completions.zsh $installdir/usr/share/zsh/site-functions/_dotnet
    # install -Dm00644 src/sdk/scripts/register-completions.ps1 $installdir/usr/share/powershell/Modules
patterns   :
    - sdk :
        - /usr/lib/dotnet/metadata
        - /usr/lib/dotnet/packs
        - /usr/lib/dotnet/sdk
        - /usr/lib/dotnet/sdk-manifests
        - /usr/lib/dotnet/templates
    - source-built-artifacts :
        - /usr/share/dotnet/source-built-artifacts
